// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLoknMMLtIT5vrs2OJyYh2RA2lfCmVzwo',
    appId: '1:997330990310:web:55926a158ca0f0c167f727',
    messagingSenderId: '997330990310',
    projectId: 'mv-web-35fcc',
    authDomain: 'mv-web-35fcc.firebaseapp.com',
    storageBucket: 'mv-web-35fcc.firebasestorage.app',
    measurementId: 'G-CYDRNDEL8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYcSo9458GBFGlcnvxHOysUZfWJbi5lQw',
    appId: '1:997330990310:android:d6b7ec16123d19c567f727',
    messagingSenderId: '997330990310',
    projectId: 'mv-web-35fcc',
    storageBucket: 'mv-web-35fcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK7DrOBuqK4G_H4yxi48wgb0KOUwMTNxI',
    appId: '1:997330990310:ios:e0765bc8a4c71dec67f727',
    messagingSenderId: '997330990310',
    projectId: 'mv-web-35fcc',
    storageBucket: 'mv-web-35fcc.firebasestorage.app',
    iosBundleId: 'com.example.mv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK7DrOBuqK4G_H4yxi48wgb0KOUwMTNxI',
    appId: '1:997330990310:ios:e0765bc8a4c71dec67f727',
    messagingSenderId: '997330990310',
    projectId: 'mv-web-35fcc',
    storageBucket: 'mv-web-35fcc.firebasestorage.app',
    iosBundleId: 'com.example.mv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLoknMMLtIT5vrs2OJyYh2RA2lfCmVzwo',
    appId: '1:997330990310:web:33342d6e8806801867f727',
    messagingSenderId: '997330990310',
    projectId: 'mv-web-35fcc',
    authDomain: 'mv-web-35fcc.firebaseapp.com',
    storageBucket: 'mv-web-35fcc.firebasestorage.app',
    measurementId: 'G-6K9G62SDBS',
  );
}
